{% set name = "buildbot-waterfall-view" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d68b1fd1679f223a20164dc1a91b17fe98d5233bddd7c5bf346f0bcae14c23f5

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - buildbot-pkg
    - setuptools
  run:
    - python >={{ python_min }}
    - buildbot-pkg
    - buildbot-www

test:
  imports:
    - buildbot_waterfall_view
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://buildbot.net/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Buildbot Waterfall View plugin
  doc_url: https://docs.buildbot.net

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
    - marcelotrevisani
