travis:
  secure:
    BINSTAR_TOKEN: zQ5klQeP/2XALR2lgn0mIwQchljpU0GwlnklessbhP0hmI8fa4IWlSlrrYI2EvWIScbpz4q1je/JJXrRHK8U7jXpLBsxct0qgVu4RSkU+xgkR5zXV9o9m2v1nRmt0WrsXJsDBptlto0D9ktD9KtxoC/FwGbNhbDrD2FjwppCJelfrgl6k096U4CryYVI4//nYwIKL0S09UENHGjVNIRB+OdDGZz6g1YW9OOqpoOpbz+c3DXu3/IHAd7UJX7y/2AbkF3UiqfOz+R+wxStCyvylrZQQ9a9xqpK34H+tTpy78nMQnn6vr9kX34DTb/RBYgkdQf2rZTjHfhdoyKbpoDGczSeMNbiGsxKDYKrz902B+yqEHuUebmGwTesN/Cur9fK+Ot2rHaLmz8XqYlh30unc7ELK2ME1PZpQ2PuPf7QhbOFWN5HQ3d1pzwTtOQ6VYLfzeZ8NJmGQ0Z9N1h1sOFixt1WWatKlgFCl9/Wo09xaUovViEthXYoVzDHiRv48w5kkHdcyYnrWKfw5QO+rpk3YTFWiCXLsHzkulIKVAzoM6Vnhhufgwav7jjuPb9m8VCO9nkuF7A8gwuB3sZeG2k2Ry3+Faxp+mtPYZ8zxWr/jPZQFBy2mPRbiY6mYqkTB1LPoQTmKStd7vQiVY/FyBTVWMjTGrN3maui4icywrazRXc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
